[package]
name = "vb-graphics-build"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
bitfield-struct = "0.12"
fontdue = "0.9"
png = "0.18"
serde = { version = "1", features = ["derive"] }
toml = "0.9"