cargo-features = ["per-package-target"]

[workspace]
members = [
    "packages/vb-graphics",
    "packages/vb-graphics-build",
    "packages/vb-rt",
    "packages/vb-rt-build",
    "examples/hello-world",
]
resolver = "3"

[profile.release]
lto = true
