cargo-features = ["per-package-target"]

[package]
name = "vb-rt"
version = "0.1.0"
edition = "2024"
forced-target = "v810-unknown-vb"

[lib]
test = false
bench = false

[dependencies]
bitfield-struct = "0.12"
fixed = "1.29"
