[package]
name = "vb-sound-build"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
midi-reader-writer = { version = "0.1", features = ["engine-midly-0-5"] }
serde = { version = "1", features = ["derive"] }
toml = "0.9"