spritesheets = [
    "assets/esma_still.toml",
    "assets/esma_walk.toml",
]

[bgspritemap.all]
bgmap_start = 0
spritesheets = [
    "assets/esma_still.toml",
    "assets/esma_walk.toml",
]

[waveform.square]
values = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 62, 62, 62, 62, 63, 63, 63, 63, 62, 62, 62, 62, 63, 63, 63, 63]

[instrument.triangle]
file = "assets/instruments/Triangle.fui"

[beepbox.waltz]
file = "assets/waltz.json"
channel.0 = { source = 0, instrument = "triangle", volume = 2.0 }
channel.1 = { source = 1, waveform = "square" }
channel.2 = { source = 2, waveform = "square" }
channel.5 = { source = 3, tap = 0 }
fixed_waveforms = ["square"]
